version: '2'
services:
    organizer-app:
        image: organizer
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://organizer-mariadb:3306/organizer
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    organizer-mariadb:
        extends:
            file: mariadb.yml
            service: organizer-mariadb
